name: Build and Release xroger PC-98 DOS Image

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm d88tool

    - name: Assemble loader.asm
      run: |
        mkdir -p build
        nasm -f bin src/loader.asm -o build/boot.bin

    - name: Assemble kernel and tasks
      run: |
        nasm -f bin src/kernel.asm -o build/kernel_part.bin
        nasm -f bin src/tasks.asm -o build/tasks.bin
        cat build/kernel_part.bin build/tasks.bin > build/kernel.bin

    - name: Create PC‑98 .d88 disk image
      run: |
        d88tool -c xroger \
                 -b build/boot.bin \
                 -k build/kernel.bin \
                 -o build/xroger.d88

    - name: Determine release tag
      id: tag
      run: echo "::set-output name=TAG::v0.1.${GITHUB_RUN_NUMBER}"

    - name: Create or update GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.TAG }}
        release_name: xroger ${{ steps.tag.outputs.TAG }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload xroger.d88 to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/xroger.d88
        asset_name: xroger.d88
        asset_content_type: application/octet-stream
